code --install-extension Catppuccin.catppuccin-vsc
code --install-extension charliermarsh.ruff
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension James-Yu.latex-workshop
code --install-extension jbenden.c-cpp-flylint
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension magicstack.MagicPython
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.cmake-tools
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension shengchen.vscode-checkstyle
code --install-extension SteveBushResearch.BuildOutputColorizer
code --install-extension twxs.cmake
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension xaver.clang-format
